### ISSUE TITLE
typo in BokehDataset&&and what is disparity in meta?  

### ISSUE THREAD

**Issue by buaawangyu** [Glass-Imaging/NTIRE23BokehTransformation#2]
1.you read src.jpg twice

2. I am confused about disparity number in meta ,can you make a clearer explain? thanks

**Comment by mako443** [comment]
Hi @buaawangyu,
Thanks for your message and good catch about the source / target mixup, I've just fixed it.

As you probably know, disparity is a measure of how much two images of the same scene differ, when they are observed from two different, nearby cameras (or eyes.) If the two cameras' locations are fixed, the difference between their images becomes greater the closer the observed objects are.

In our case, we use a notion of "qualitative disparity" as a broad metric for inverse distance, i.e. the higher the disparity, the more blurry the image is. This disparity value is calibrated such that it corresponds to a set of real-world captures that might be part of our test data (more news on that coming soon.)

Our reason for using a) disparity instead of distance and b) a qualitative, calibrated metric instead of an exact one is that we cannot find an actual, metric distance for the images in our training data, since their originals are downloaded from the web.
What we can do however, is calibrate the amount of blur in them such that it matches up to our real-world images.
This approach is inspired by previous work such as [MiDaS](https://arxiv.org/abs/1907.01341v3), which is also based on a notion of disparity, rather than requiring exact distances.

I hope this answers your great question, we will add this to our explanation of the data.
If not, please feel free to re-open and ask further questions.
